spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  mvc:
    hiddenmethod:
      filter:
        enabled: true

comment:
  avatar: /images/avatar.jpg
normal_avatar:
  url: "http://cdn.roxysaikou.top/%E5%A4%B4%E5%83%8F/normalUserAvatar/"
  number: 2
snow_flake:
  machine_id: 37
  data_center_id: 3

async:
  executor:
    thread:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 99999
      name:
        prefix: async-service-